# Generated by Django 5.0.2 on 2024-02-26 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('project_id', 'user_id')},
        ),
    ]
