# Generated by Django 5.0.2 on 2024-02-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0003_issue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('project', 'title')},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='contributor',
        ),
    ]
