# Generated by Django 5.0.2 on 2024-03-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0003_rename_project_id_contributor_project_and_more'),
    ]

    operations = [
    ]
