# Generated by Django 5.0.2 on 2024-03-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0004_auto_20240301_1803'),
    ]

    operations = [
    ]
