# Generated by Django 5.0.2 on 2024-03-01 17:28

import api_project.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0005_auto_20240301_1809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='issue',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(default=api_project.models.get_default_project_id, on_delete=django.db.models.deletion.CASCADE, to='api_project.project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
