# Generated by Django 5.0.2 on 2024-03-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0006_remove_comment_commenter_remove_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
