# Generated by Django 5.0.2 on 2024-03-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0007_remove_comment_status'),
    ]

    operations = [
    ]
