# Generated by Django 5.0.2 on 2024-03-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0009_project_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
    ]
