# Generated by Django 5.0.2 on 2024-03-06 15:28

import api_project.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0011_alter_comment_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(default=api_project.models.get_default_project_id, on_delete=django.db.models.deletion.CASCADE, to='api_project.project'),
        ),
    ]
