# Generated by Django 5.0.2 on 2024-02-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
