# Generated by Django 5.0.2 on 2024-02-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_customuser_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='consent',
        ),
    ]
